# Generated by Django 2.1 on 2018-11-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_slider_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='span',
        ),
        migrations.AddField(
            model_name='slider',
            name='sub_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Sub Title'),
        ),
    ]
