# Generated by Django 2.1.4 on 2018-12-20 19:03

import ckeditor.fields
from django.db import migrations, models
import optimized_image.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_seo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title Seo')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image_preview', optimized_image.fields.OptimizedImageField(blank=True, upload_to='', verbose_name='Images')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Images Alt')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('-created_at',),
            },
        ),
    ]
