# Generated by Django 2.0 on 2018-01-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
