# Generated by Django 2.0.6 on 2018-06-07 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180606_0629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostModel',
            new_name='Article',
        ),
    ]
