# Generated by Django 4.1.2 on 2023-04-22 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pattern",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    django_extensions.db.fields.ShortUUIDField(
                        blank=True, editable=False, verbose_name="pattern_uuid"
                    ),
                ),
                ("prompt", models.TextField(verbose_name="pattern_prompt")),
                (
                    "created_up",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="request time"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattern_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
        ),
    ]
