# Generated by Django 4.1.2 on 2022-12-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercart",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("AWAITING", "Awaiting pay"),
                    ("CREATING", "Creating"),
                    ("SHIPPING", "Shipping"),
                    ("COMPLETED", "Completed"),
                    ("CANCELED", "Canceled"),
                ],
                default="NEW",
                max_length=14,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
