# Generated by Django 4.1.2 on 2022-11-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercart',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('AWAITING', 'Awaiting pay'), ('CREATING', 'Creating'), ('SHIPPING', 'Shipping'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='NEW', max_length=14, verbose_name='Status'),
        ),
    ]
