# Generated by Django 4.1.2 on 2023-04-05 08:29

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                populate_from="title",
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
