# Generated by Django 4.1.2 on 2023-03-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_ordercart_status_alter_product_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordercart",
            name="order_total_cost_currency",
        ),
        migrations.RemoveField(
            model_name="ordercartitem",
            name="item_total_cost_currency",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price_currency",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sale_currency",
        ),
        migrations.AddField(
            model_name="ordercart",
            name="currency",
            field=models.CharField(
                default="EUR", max_length=3, verbose_name="Currency"
            ),
        ),
        migrations.AddField(
            model_name="ordercartitem",
            name="currency",
            field=models.CharField(
                default="EUR", max_length=3, verbose_name="Currency"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(
                default="EUR", max_length=3, verbose_name="Currency"
            ),
        ),
        migrations.AlterField(
            model_name="ordercart",
            name="order_total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Total cost order",
            ),
        ),
        migrations.AlterField(
            model_name="ordercartitem",
            name="item_total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Total cost item order",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Sale",
            ),
        ),
    ]
