# Generated by Django 3.0.2 on 2020-01-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_ordercart_ordercartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='product_colors', to='shop.ProductColor', verbose_name='Colors'),
        ),
    ]
