# Generated by Django 4.1.2 on 2023-03-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_remove_ordercart_order_total_cost_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="meta_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
    ]
