# Generated by Django 3.0.2 on 2020-03-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_auto_20200227_1551"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordercart",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
