# Generated by Django 3.0.2 on 2020-03-28 19:01

from django.db import migrations
import django_extensions.db.fields
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_auto_20200328_1933"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AddField(
            model_name="ordercart",
            name="order_number",
            field=django_extensions.db.fields.ShortUUIDField(
                blank=True, editable=False, null=True, verbose_name="Number order"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title", verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="RUB",
                max_digits=14,
                null=True,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "EUR €"), ("RUB", "RUB ₽"), ("USD", "USD $")],
                default="RUB",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="RUB",
                max_digits=14,
                null=True,
                verbose_name="Sale",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "EUR €"), ("RUB", "RUB ₽"), ("USD", "USD $")],
                default="RUB",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title", verbose_name="slug"
            ),
        ),
    ]
