# Generated by Django 3.0.6 on 2020-05-24 15:13

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_add_fk_order_cart_and_del_mtm_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercart",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="ordercart",
            name="order_number",
            field=django_extensions.db.fields.ShortUUIDField(
                blank=True, default=None, editable=False, verbose_name="Number order"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordercartitem",
            name="amount",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Amount"),
        ),
    ]
