# Generated by Django 3.0.6 on 2020-05-29 12:08

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_email_field_null_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordercart",
            name="order_total_cost",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="RUB",
                max_digits=14,
                null=True,
                verbose_name="Total cost order",
            ),
        ),
        migrations.AddField(
            model_name="ordercart",
            name="order_total_cost_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "EUR €"), ("RUB", "RUB ₽"), ("USD", "USD $")],
                default="RUB",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="ordercartitem",
            name="item_total_cost",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="RUB",
                max_digits=14,
                null=True,
                verbose_name="Total cost item order",
            ),
        ),
        migrations.AddField(
            model_name="ordercartitem",
            name="item_total_cost_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "EUR €"), ("RUB", "RUB ₽"), ("USD", "USD $")],
                default="RUB",
                editable=False,
                max_length=3,
            ),
        ),
    ]
