# Generated by Django 3.0.6 on 2020-05-29 12:29

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_add_total_costs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercart",
            name="order_total_cost",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                default_currency="RUB",
                max_digits=14,
                verbose_name="Total cost order",
            ),
        ),
        migrations.AlterField(
            model_name="ordercartitem",
            name="item_total_cost",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                default_currency="RUB",
                max_digits=14,
                verbose_name="Total cost item order",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                default_currency="RUB",
                max_digits=14,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                default_currency="RUB",
                max_digits=14,
                verbose_name="Sale",
            ),
        ),
    ]
