# Generated by Django 3.0.2 on 2020-03-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
    ]
