EMAIL_BACKEND = 'mailer.backend.DbBackend'

EMAIL_USE_TLS = False
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 2525
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = ''
# SENDGRID_PASSWORD = '2H6ScE491gp'
