# Generated by Django 3.0.2 on 2020-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200223_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Address'),
        ),
    ]
