# Generated by Django 3.0.2 on 2020-02-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_add_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="Phone number"
            ),
        ),
    ]
