# Generated by Django 3.0.6 on 2020-06-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_auto_20200228_1351"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("AUTHOR", "Author"),
                    ("MANAGER", "Manager"),
                    ("CLIENT", "Client"),
                ],
                default="CLIENT",
                max_length=63,
                verbose_name="Type user",
            ),
        ),
    ]
