# Generated by Django 4.1.2 on 2023-03-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="model_type",
            field=models.CharField(
                blank=True,
                choices=[("ARTICLE", "Article"), ("COMMENT", "Comment")],
                default="ARTICLE",
                max_length=20,
                verbose_name="Model type",
            ),
        ),
    ]
