# Generated by Django 4.1.2 on 2023-03-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reactions", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("model_type", "model_id", "reaction"), name="unique_reaction"
            ),
        ),
    ]
