# Generated by Django 2.1.4 on 2018-12-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='keywords',
            new_name='meta_keywords',
        ),
    ]
