INSTALLED_APPS = [
    "modeltranslation",
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # 'django.contrib.sites',
    # Plugins
    # Auth2
    # "oauth2_provider",
    # "social_django",
    # "rest_framework_social_oauth2",
    "graphene_django",
    "corsheaders",
    "django_extensions",
    "mptt",
    "ckeditor",
    "ckeditor_uploader",
    "optimized_image",
    "djmoney",
    "djmoney.contrib.exchange",
    "colorful",
    # Django Rest Framework
    "rest_framework",
    "rest_framework_swagger",
    "rest_framework_simplejwt.token_blacklist",
    "drf_yasg",
    # Apps project
    "src.apps.api",
    "src.apps.blog",
    "src.apps.shop",
    "src.apps.menu",
    "src.apps.account",
    "src.apps.subscribe",
    "src.apps.contacts",
    "src.apps.slider",
    "src.apps.reviews",
]
