# Generated by Django 4.1.2 on 2022-12-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_en",
            field=models.TextField(blank=True, null=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Content"),
        ),
    ]
