# Generated by Django 4.1.2 on 2023-05-24 09:33

from django.db import migrations, models
import optimized_image.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_bookmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text content")),
                (
                    "image",
                    optimized_image.fields.OptimizedImageField(
                        blank=True, upload_to="", verbose_name="Images"
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Images Alt"
                    ),
                ),
            ],
            options={
                "verbose_name": "content",
                "verbose_name_plural": "contents",
            },
        ),
        migrations.RemoveField(
            model_name="article",
            name="image_alt",
        ),
        migrations.RemoveField(
            model_name="article",
            name="image_preview",
        ),
        migrations.AddField(
            model_name="article",
            name="contents",
            field=models.ManyToManyField(
                blank=True,
                related_name="contents",
                to="blog.articlecontent",
                verbose_name="ArticleContent",
            ),
        ),
    ]
