# Generated by Django 3.0.2 on 2020-03-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20200106_1420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(max_length=64, unique=True, verbose_name="Slug"),
        ),
    ]
