# Generated by Django 4.1.2 on 2023-03-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_article_content_alter_article_content_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.CharField(
                max_length=63, null=True, verbose_name="Description"
            ),
        ),
    ]
