# Generated by Django 4.1.2 on 2023-03-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_article_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="meta_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="meta_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="meta_description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="meta_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="meta_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="meta_description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
    ]
