# Generated by Django 4.1.2 on 2023-03-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_article_meta_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description_en",
            field=models.CharField(
                max_length=63, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="description_ru",
            field=models.CharField(
                max_length=63, null=True, verbose_name="Description"
            ),
        ),
    ]
