# Generated by Django 4.1.2 on 2023-04-04 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=263, verbose_name="Text")),
                (
                    "model_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ARTICLE", "Article"),
                            ("COMMENT", "Comment"),
                            ("COURSE", "Course"),
                            ("PRODUCT", "Product"),
                        ],
                        default="COMMENT",
                        max_length=20,
                        verbose_name="Model type",
                    ),
                ),
                (
                    "model_id",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Associated"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
    ]
