# Generated by Django 4.1.2 on 2023-03-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_alter_comment_options_remove_comment_to_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="meta_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta_Description"
            ),
        ),
    ]
