# Generated by Django 3.0.2 on 2020-01-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='active',
            new_name='is_active',
        ),
    ]
