# Generated by Django 3.0.2 on 2020-03-28 19:01

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("slider", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slider",
            options={
                "ordering": ("ordering",),
                "verbose_name": "Slider",
                "verbose_name_plural": "Sliders",
            },
        ),
        migrations.AlterField(
            model_name="slider",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title", verbose_name="slug"
            ),
        ),
    ]
